
# Bar, wallpaper
# exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh
exec-once = hyprpaper
exec-once = foot --server

# Input method
# exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk

# Audio
exec-once = easyeffects --gapplication-service

# Clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Top bar and tray
exec-once = waybar -c $HOME/.config/waybar/config.jsonc
exec-once = waybar -c $HOME/.config/waybar/config_L.jsonc
exec-once = waybar -c $HOME/.config/waybar/config_R.jsonc

# exec-once = ironbar

exec-once = sleep 5 && $HOME/.local/share/launch-scripts/launch-nwg.sh &


# ========== MY EXECS =========
exec-once = kdeconnectd
exec-once = kdeconnect-indicator

# exec-once = [workspace 2 silent] $browser
exec-once = [workspace 2 silent] ferdium
# exec-once = [workspace 5 silent] gnome-calendar
exec-once = [workspace 6 silent] $terminal

exec-once = [workspace special:magic silent] obsidian