# From execs.conf, move these:
$terminal = kitty
$notes = obsidian
$menu = /home/tefloon/.config/wofi/wofi-toggle.sh
$mainMod = SUPER
$fileManager = dolphin
$editor = subl
$browser = thorium-browser
$launchScripts = /home/tefloon/.local/share/launch-scripts

# You might also want to add animation/styling variables:
$animSpeed = 2
$opacity = 0.85