# From execs.conf, move these:
$terminal = kitty
$notes = obsidian
$menu = $HOME/.config/wofi/wofi-toggle.sh
$mainMod = SUPER
$fileManager = nautilus --new-window
$editor = subl
$browser = helium-browser
$launchScripts = $HOME/.local/share/launch-scripts

# You might also want to add animation/styling variables:
$animSpeed = 2
$opacity = 0.85