#!/usr/bin/env bash

SUBSCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SUBSCRIPT_DIR/../status.sh"

CURRENT_STEP_MESSAGE="Setting up default browser"
status_msg

# Paths
BROWSER_CONF="$HOME/.config/default-apps/browser.conf"
BROWSER_ENV="$HOME/.config/default-apps/generated-env.sh"

# Read browser preference
if [ ! -f "$BROWSER_CONF" ]; then
    status_skip "Browser config not found at $BROWSER_CONF"
    exit 0
fi

BROWSER=$(cat "$BROWSER_CONF" | tr -d '[:space:]')

if [ -z "$BROWSER" ]; then
    status_skip "Browser config is empty"
    exit 0
fi

DESKTOP_FILE="${BROWSER}.desktop"

# Check if .desktop file exists
if ! command -v "$BROWSER" &> /dev/null && [ ! -f "/usr/share/applications/${DESKTOP_FILE}" ] && [ ! -f "$HOME/.local/share/applications/${DESKTOP_FILE}" ]; then
    status_skip "Browser '$BROWSER' not found on system"
    exit 0
fi

# Set XDG MIME associations (idempotent - safe to run multiple times)
xdg-mime default "$DESKTOP_FILE" x-scheme-handler/http 2>/dev/null
xdg-mime default "$DESKTOP_FILE" x-scheme-handler/https 2>/dev/null
xdg-mime default "$DESKTOP_FILE" text/html 2>/dev/null

# Generate environment file for shell sourcing
cat > "$BROWSER_ENV" << EOF
# Auto-generated by setup_default_browser.sh
# DO NOT EDIT MANUALLY - Edit ~/.config/default-apps/browser.conf instead
export BROWSER="$BROWSER"
EOF

chmod 644 "$BROWSER_ENV"

status_ok