# Disable IPC for better battery life
# ipc = off

# Preload Kath's contest-winning wallpaper
preload = $HOME/.local/share/wallpapers/kath.png
preload = $HOME/.local/share/wallpapers/download.png

# Set wallpaper for all monitors (empty monitor = fallback)
wallpaper {
    monitor = 
    path = $HOME/.local/share/wallpapers/kath.png
    fit_mode = cover
}
splash = false