# Use stronger algorithms
cipher-algo AES256         
digest-algo SHA512         
cert-digest-algo SHA512    
compress-algo 2            

# Display preferences  
keyid-format 0xlong
# Show fingerprints
with-fingerprint
charset utf-8